### ISSUE TITLE
Unable to use EC2 instance profile

### ISSUE THREAD

**Issue by jekh** [jenkinsci/aws-credentials-plugin#29]
I just installed the latest version of the plugin with the assume role support included from PR #20. I've got an EC2 slave with an IAM role of `jenkins-ec2`, and I've created an IAM role called `jenkins-role` that I'm trying to get jenkins to assume. I've configured the credentials plugin with no access key or secret, but with a Task Role of my assumable `jenkins-role` role. (And I've set up the trust relationship appropriately, so `jenkins-role` is assumable by `jenkins-ec2`.)

When my job starts, I get this error:

```
Started by user Jason Hoetger
[EnvInject] - Loading node environment variables.
Building remotely on jenkins-u16-3 (jenkins jenkins-u16) in workspace /home/ubuntu/workspace/assume-role-test
FATAL: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/
com.amazonaws.SdkClientException: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:115)
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:77)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:156)
	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121)
	at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:141)
	at com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl.getCredentials(AWSCredentialsImpl.java:119)
	at com.cloudbees.jenkins.plugins.awscredentials.AmazonWebServicesCredentialsBinding.bind(AmazonWebServicesCredentialsBinding.java:97)
	at org.jenkinsci.plugins.credentialsbinding.impl.SecretBuildWrapper.setUp(SecretBuildWrapper.java:59)
	at hudson.model.Build$BuildExecution.doRun(Build.java:156)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1729)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Finished: FAILURE
```

It looks like it's trying to get metadata from `http://169.254.169.254/latest/meta-data/iam/security-credentials/`. When I hop on the box, I can confirm that that URL returns nothing, but adding the role name as indicated in the [AWS docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) does, in fact, return the appropriate credentials.

In other words, `http://169.254.169.254/latest/meta-data/iam/security-credentials/jenkins-ec2` returns the EC2 instance credentials. The `jenkins-ec2` role name appears to be missing from the endpoint it's trying to hit.

Any idea why this might be happening? Have I misconfigured my plugin? Is the `InstanceProfileCredentialsProvider` from the AWS SDK being properly instantiated and used properly in PR #20?

I'm wondering if it might be better to avoid explicitly instantiating the `InstanceProfileCredentialsProvider` and simply allow the AWS SDK to get credentials using its the [default provider chain](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-roles.html#default-provider-chain). That would also have the advantage of allowing the assume role support to work with ECS Task Roles, since the AWS SDK already knows how to fetch those credentials using the default provider chain.

**Comment by ConstantinElse** [comment]
I'm facing the same issue - I cannot get the AWS credentials plugin to use the EC2 instance profile/role.

Despite Jenkins node is running on EC2 with proper role & permissions policies - I cannot use it further in amazon-ecr to login ...

The workaround was to create an IAM user with access/secret keys and add it to Jenkins but I think this is ugly solution.

Any idea how to make the AWS credentials plugin become `aware` of instance role and use those temporary credentials (by default) ?

**Comment by alexejk** [comment]
If you do not have an instance profile assigned to your instance - even SDK will not be able to get credentials that will be enough. It's only initiated when a role link is provided which is needed when working cross boundaries of AWS accounts. You can leave role empty and just assign a role with correct permissions to your master and it should work
